
version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx
      - ./nginx/certs:/etc/ssl/private
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nextjs:
    build: ./frontend/nextjs
    ports:
      - 3000:3000

  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    volumes:
      - ./backend/app:/srv/app
    ports:
      - 1337:1337 
    depends_on:
      - db
#    command: yarn add strapi-plugin-graphql

  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - 5432:5432   
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
